name: id-token permissions (none)
run-name: ${{ github.actor }} is testing id-token permissions (none)
on: [push, workflow_dispatch]


permissions:
  id-token: none

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
